# This is a generated file. Not intended for manual editing.
services:
  administration:
    build:
      context: "/home/mplopes/Documentos/Dyson"
      dockerfile: "Administration/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Administration.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "administration:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/mplopes/Documentos/Dyson/Administration:/app:rw"
    - "/home/mplopes/Documentos/Dyson:/src:rw"
    - "/home/mplopes/.nuget/packages:/home/app/.nuget/packages"
    - "/home/mplopes/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.4/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/var/lib/snapd/snap/rider/681/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/mplopes/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_13_16_37_37:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  api:
    build:
      context: "/home/mplopes/Documentos/Dyson"
      dockerfile: "Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "api:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/home/mplopes/Documentos/Dyson/Api:/app:rw"
    - "/home/mplopes/Documentos/Dyson:/src:rw"
    - "/home/mplopes/.nuget/packages:/home/app/.nuget/packages"
    - "/home/mplopes/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.4/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/var/lib/snapd/snap/rider/681/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/mplopes/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_13_16_37_37:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  application:
    build:
      context: "/home/mplopes/Documentos/Dyson"
      dockerfile: "Application/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57402"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/GalileuApp.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "application:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57402"
    volumes:
    - "/home/mplopes/Documentos/Dyson/Application:/app:rw"
    - "/home/mplopes/Documentos/Dyson:/src:rw"
    - "/home/mplopes/.nuget/packages:/home/app/.nuget/packages"
    - "/home/mplopes/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.4/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/var/lib/snapd/snap/rider/681/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/mplopes/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_13_16_37_37:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
